"""Client-facing communication intelligence for Aliyar Solutions."""
from __future__ import annotations

import re
from typing import Optional


BLOCKED_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    ("Qualified by JARVIS", "Qualified through operational review"),
    ("Generated by JARVIS", "Prepared by Aliyar Solutions"),
    ("Reviewed by JARVIS", "Reviewed by our operations team"),
    ("JARVIS identified", "Our consulting team identified"),
    ("JARVIS recommends", "Our operations team recommends"),
    ("JARVIS prepared", "Our operations team prepared"),
    ("JARVIS Revenue Engine", "Aliyar Solutions Revenue Workflow"),
    ("AI-powered", "technology-enabled"),
    ("AI automation and cloud operations", "workflow automation and cloud operations"),
    ("AI automation", "workflow automation"),
    ("cloud/AI operations", "cloud and workflow operations"),
    ("JARVIS", "Aliyar Solutions"),
    ("Jarvis", "Aliyar Solutions"),
    ("jarvis", "Aliyar Solutions"),
    ("AI-generated", "consulting-prepared"),
    ("AI generated", "consulting-prepared"),
    ("machine-generated proposal", "consulting proposal"),
    ("AI agent", "operations specialist"),
    ("AI agents", "operations specialists"),
    ("autonomous system", "managed operating process"),
    ("autonomous worker", "operations specialist"),
    ("digital brain", "operational intelligence layer"),
    ("orchestration system", "operating workflow"),
    ("workflow AI", "workflow analysis"),
    ("provider routing", "service routing"),
    ("model switching", "service routing"),
    ("reasoning chains", "internal review notes"),
    ("internal prompts", "internal review notes"),
    ("OpenAI", "our technology team"),
    ("Claude", "our technology team"),
    ("Anthropic", "our technology team"),
    ("DeepSeek", "our technology team"),
    ("Bedrock", "our cloud team"),
    ("Groq", "our technology team"),
    ("NVIDIA", "our technology team"),
    ("Nvidia", "our technology team"),
)

BLOCKED_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"\bAI\s+orchestration\b", re.I), "operational coordination"),
    (re.compile(r"\bAI\s+tool(?:s)?\b", re.I), "workflow systems"),
    (re.compile(r"\bchatbot\b", re.I), "support workflow"),
    (re.compile(r"\bbot\b", re.I), "workflow assistant"),
)


def sanitize_client_text(value: Optional[str]) -> str:
    """Remove internal system language from client-visible copy."""
    if not value:
        return ""
    text = str(value)
    for old, new in BLOCKED_REPLACEMENTS:
        text = text.replace(old, new)
    for pattern, replacement in BLOCKED_PATTERNS:
        text = pattern.sub(replacement, text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def sanitize_subject_body(subject: Optional[str], body: Optional[str]) -> tuple[str, str]:
    return sanitize_client_text(subject), sanitize_client_text(body)
