"""Client-facing communication intelligence for Aliyar Solutions.

This module is the boundary between internal operating-system language and
external consulting communication. Anything saved as outreach, proposal, or
client-visible copy should pass through this layer.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Iterable, Optional


BLOCKED_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    ("Qualified by JARVIS", "Qualified through operational review"),
    ("Generated by JARVIS", "Prepared by Aliyar Solutions"),
    ("Reviewed by JARVIS", "Reviewed by our operations team"),
    ("JARVIS identified", "Our consulting team identified"),
    ("JARVIS recommends", "Our operations team recommends"),
    ("JARVIS prepared", "Our operations team prepared"),
    ("JARVIS Revenue Engine", "Aliyar Solutions Revenue Workflow"),
    ("JARVIS revenue engine", "Aliyar Solutions revenue workflow"),
    ("Already qualified by Aliyar Solutions", "Strong fit based on current operating profile"),
    ("AI automation and cloud operations", "workflow automation and cloud operations"),
    ("AI automation", "workflow automation"),
    ("cloud/AI operations", "cloud and workflow operations"),
    ("AI-powered", "technology-enabled"),
    ("JARVIS", "Aliyar Solutions"),
    ("Jarvis", "Aliyar Solutions"),
    ("jarvis", "Aliyar Solutions"),
    ("AI-generated", "consulting-prepared"),
    ("AI generated", "consulting-prepared"),
    ("machine-generated proposal", "consulting proposal"),
    ("AI agent", "operations specialist"),
    ("AI agents", "operations specialists"),
    ("autonomous system", "managed operating process"),
    ("autonomous worker", "operations specialist"),
    ("digital brain", "operational intelligence layer"),
    ("automation engine", "workflow improvement process"),
    ("orchestration system", "operating workflow"),
    ("workflow AI", "workflow analysis"),
    ("provider routing", "service routing"),
    ("model switching", "service routing"),
    ("reasoning chains", "internal review notes"),
    ("internal prompts", "internal review notes"),
    ("provider chains", "service routing"),
    ("fallback systems", "continuity processes"),
    ("OpenAI", "our technology team"),
    ("Claude", "our technology team"),
    ("Anthropic", "our technology team"),
    ("DeepSeek", "our technology team"),
    ("Bedrock", "our cloud team"),
    ("Groq", "our technology team"),
    ("NVIDIA", "our technology team"),
    ("Nvidia", "our technology team"),
)

BLOCKED_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"\bAI\s+orchestration\b", re.I), "operational coordination"),
    (re.compile(r"\bAI\s+tool(?:s)?\b", re.I), "workflow systems"),
    (re.compile(r"\bchatbot\b", re.I), "support workflow"),
    (re.compile(r"\bbot\b", re.I), "workflow assistant"),
)

BASIC_INDUSTRIES = {
    "clinic", "clinics", "restaurant", "salon", "dentist", "doctor", "local",
    "cafe", "shop", "retail", "gym", "spa", "agency", "startup",
}
ENTERPRISE_INDUSTRIES = {
    "enterprise", "hospital", "healthcare group", "logistics", "finance",
    "insurance", "bank", "government", "education", "university",
    "manufacturing", "infrastructure", "multi-location",
}


@dataclass(frozen=True)
class ClientProfile:
    company_name: str
    contact_name: str
    industry: str
    company_size: str
    revenue_range: str
    country: str
    pain_points: tuple[str, ...]
    maturity_tier: str
    division: str
    tone: str


def sanitize_client_text(value: Optional[str]) -> str:
    """Remove internal system language from client-visible copy."""
    if not value:
        return ""
    text = str(value)
    for old, new in BLOCKED_REPLACEMENTS:
        text = text.replace(old, new)
    for pattern, replacement in BLOCKED_PATTERNS:
        text = pattern.sub(replacement, text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def _lower(value: Optional[str]) -> str:
    return str(value or "").strip().lower()


def _company_size_score(size: str) -> int:
    text = _lower(size)
    if any(token in text for token in ("1000", "enterprise", "500+", "large")):
        return 3
    if any(token in text for token in ("200", "201", "500", "51-200", "50-200")):
        return 2
    if any(token in text for token in ("50", "11-50", "10-50")):
        return 1
    return 0


def build_client_profile(contact=None, company=None, lead=None, service_type: str = "") -> ClientProfile:
    company_name = (
        getattr(company, "name", None)
        or getattr(getattr(contact, "company", None), "name", None)
        or getattr(lead, "company", None)
        or getattr(lead, "company_name", None)
        or "your organization"
    )
    contact_name = getattr(contact, "name", None) or getattr(lead, "contact_name", None) or "there"
    industry = (
        getattr(company, "industry", None)
        or getattr(getattr(contact, "company", None), "industry", None)
        or getattr(lead, "industry", None)
        or service_type
        or "operations"
    )
    size = (
        getattr(company, "size", None)
        or getattr(getattr(contact, "company", None), "size", None)
        or ""
    )
    revenue = (
        getattr(company, "revenue_range", None)
        or getattr(getattr(contact, "company", None), "revenue_range", None)
        or ""
    )
    country = (
        getattr(contact, "country", None)
        or getattr(company, "country", None)
        or getattr(getattr(contact, "company", None), "country", None)
        or getattr(lead, "country", None)
        or ""
    )
    pain_points = tuple(
        str(item)
        for item in (
            getattr(company, "pain_points", None)
            or getattr(getattr(contact, "company", None), "pain_points", None)
            or getattr(lead, "pain_points", None)
            or []
        )
        if item
    )

    score = _company_size_score(size)
    industry_text = _lower(industry)
    if any(word in industry_text for word in ENTERPRISE_INDUSTRIES):
        score += 2
    if any(word in industry_text for word in BASIC_INDUSTRIES):
        score -= 1
    if any(token in _lower(revenue) for token in ("50m", "100m", "enterprise")):
        score += 2

    if score >= 3:
        tier = "enterprise"
        tone = "executive, strategic, boardroom-ready"
        division = "Aliyar Solutions - AI & Cloud Operations Division"
    elif score >= 1:
        tier = "standard"
        tone = "professional, structured, consultative"
        division = "Aliyar Solutions Operations Consulting Team"
    else:
        tier = "basic"
        tone = "warm, practical, clear"
        division = "Aliyar Solutions Enterprise Automation Team"

    return ClientProfile(
        company_name=sanitize_client_text(company_name),
        contact_name=sanitize_client_text(contact_name),
        industry=sanitize_client_text(industry),
        company_size=sanitize_client_text(size),
        revenue_range=sanitize_client_text(revenue),
        country=sanitize_client_text(country),
        pain_points=tuple(sanitize_client_text(item) for item in pain_points),
        maturity_tier=tier,
        division=division,
        tone=tone,
    )


def consulting_reasons(reasons: Iterable[str]) -> list[str]:
    clean = []
    for reason in reasons:
        text = sanitize_client_text(str(reason))
        text = text.replace("ICP", "target-market")
        text = text.replace("Already qualified during operational review", "Strong fit based on current operating profile")
        if text:
            clean.append(text)
    return clean or ["Current workflow profile suggests room for operational improvement"]


def build_outreach_draft(profile: ClientProfile, service_type: str, reasons: Iterable[str]) -> tuple[str, str]:
    company = profile.company_name
    contact_value = (profile.contact_name or "").strip()
    first_name = "there" if contact_value.lower() == company.lower() else (contact_value or "there").split()[0]
    reasons_text = "; ".join(consulting_reasons(reasons)[:3])
    service = sanitize_client_text(service_type or "workflow automation")

    if profile.maturity_tier == "enterprise":
        subject = f"Operational modernization review for {company}"
        body = (
            f"Hi {first_name},\n\n"
            f"Following our review of {company}'s operating profile, we noticed indicators that may justify a structured workflow modernization assessment. "
            f"The main signals were: {reasons_text}.\n\n"
            f"Aliyar Solutions helps organizations improve execution consistency, operational visibility, and response reliability through carefully scoped {service.lower()} initiatives. "
            "The objective is to reduce operational overhead while improving execution speed and governance.\n\n"
            "If useful, our team can prepare a concise operational assessment showing the highest-value workflow improvements for your environment.\n\n"
            "Regards,\n"
            "Aliyar Solutions - AI & Cloud Operations Division"
        )
    elif profile.maturity_tier == "standard":
        subject = f"Workflow improvement opportunity for {company}"
        body = (
            f"Hi {first_name},\n\n"
            f"Based on our operational review of {company}, we believe there may be practical opportunities to improve coordination and reduce repetitive manual work. "
            f"The main signals were: {reasons_text}.\n\n"
            f"Our operations team helps growing organizations streamline {service.lower()}, improve reporting visibility, and reduce avoidable delays without making systems harder to manage.\n\n"
            "Would it be useful if we sent a short assessment with the clearest workflow improvements we see?\n\n"
            "Warm regards,\n"
            "Aliyar Solutions Operations Consulting Team"
        )
    else:
        subject = f"A practical workflow idea for {company}"
        body = (
            f"Hi {first_name},\n\n"
            f"I came across {company} and noticed a few signs that simple workflow improvements could save time and make day-to-day operations easier. "
            f"The main signals were: {reasons_text}.\n\n"
            "Aliyar Solutions helps teams reduce repetitive tasks, organize follow-ups, and improve response speed through practical workflow improvements that stay easy to manage.\n\n"
            "If helpful, we can share a short, plain-English review of where time may be getting lost and what could be improved first.\n\n"
            "Warm regards,\n"
            "Aliyar Solutions Enterprise Automation Team"
        )
    return sanitize_client_text(subject), sanitize_client_text(body)


def build_proposal_draft(
    profile: ClientProfile,
    service_type: str,
    score: int,
    reasons: Iterable[str],
    pricing: dict,
) -> str:
    company = profile.company_name
    contact = profile.contact_name or "there"
    greeting = "Hello" if contact.lower() == company.lower() else f"Hi {contact}"
    service = sanitize_client_text(service_type or "workflow automation")
    reason_text = "; ".join(consulting_reasons(reasons)[:4])
    setup_fee = int(float(pricing.get("setup_fee") or pricing.get("one_time") or 0))
    retainer = int(float(pricing.get("monthly_retainer") or 0))

    if profile.maturity_tier == "enterprise":
        opening = "Following our operational assessment"
        risk = "fragmented visibility, inconsistent execution, and avoidable operational overhead across teams or locations"
        outcome = "improved governance, execution reliability, scalable visibility, and reduced operational drag"
        phase_label = "Implementation phases"
        closing = "Regards,\nAliyar Solutions - AI & Cloud Operations Division"
    elif profile.maturity_tier == "standard":
        opening = "Based on our workflow analysis"
        risk = "manual coordination gaps, delayed follow-ups, and limited visibility across active work"
        outcome = "faster response times, clearer reporting, improved coordination, and fewer repetitive tasks"
        phase_label = "Suggested implementation phases"
        closing = "Warm regards,\nAliyar Solutions Operations Consulting Team"
    else:
        opening = "After reviewing the current operating profile"
        risk = "repetitive manual work, missed follow-ups, and avoidable confusion during busy periods"
        outcome = "saved hours, simpler daily operations, faster responses, and a clearer follow-up process"
        phase_label = "Simple implementation plan"
        closing = "Warm regards,\nAliyar Solutions Enterprise Automation Team"

    content = f"""
{greeting},

{opening} for {company}, we see a strong opportunity to improve day-to-day operations through {service}.

Company context
{company} appears to operate in the {profile.industry or 'operations'} space, where response speed, coordination, and consistent follow-through can directly affect customer experience and internal efficiency.

Observed workflow inefficiencies
Our consulting team identified the following fit signals: {reason_text}.

Operational risks or bottlenecks
The current workflow may be exposed to {risk}. These issues usually increase workload, slow response times, and make performance harder to measure as demand grows.

Recommended transformation scope
1. Map the current workflow and identify the highest-friction handoffs.
2. Design a focused workflow improvement layer for intake, follow-up, reporting, and coordination.
3. Implement the first operational workflow with clear ownership, documentation, and review points.
4. Add visibility so leadership can see progress, delays, and next actions without chasing updates manually.

Expected operational outcomes
The proposed workflow is designed to deliver {outcome}. The objective is to reduce operational overhead while improving execution speed and consistency.

{phase_label}
Phase 1: Operational review and workflow mapping.
Phase 2: Implementation of the highest-impact workflow improvements.
Phase 3: Reporting, handover, and optimization based on real usage.

Pricing / investment
Recommended setup investment: ${setup_fee:,}.
Optional monthly support: ${retainer:,} per month.

ROI / operational value
The investment is intended to recover itself through saved operational hours, reduced delays, better coordination, and more consistent execution quality.

Strategic positioning
This is not about adding complexity. The goal is to create a cleaner operating structure that helps the team focus on higher-value work instead of repetitive manual processes.

{closing}
"""
    return sanitize_client_text(content)


def sanitize_subject_body(subject: Optional[str], body: Optional[str]) -> tuple[str, str]:
    return sanitize_client_text(subject), sanitize_client_text(body)
