const MODELS = {
  // Anthropic
  'claude-sonnet': {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    provider: 'anthropic',
    color: '#d97706',
    icon: '🧠',
    strengths: ['code', 'reasoning', 'analysis', 'writing'],
    contextWindow: 200000,
    envKey: 'ANTHROPIC_API_KEY',
  },
  'claude-opus': {
    id: 'claude-opus-4-7',
    name: 'Claude Opus 4.7',
    provider: 'anthropic',
    color: '#b45309',
    icon: '🧠',
    strengths: ['complex-reasoning', 'research', 'creative'],
    contextWindow: 200000,
    envKey: 'ANTHROPIC_API_KEY',
  },
  // OpenAI
  'gpt-4o': {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    color: '#16a34a',
    icon: '⚡',
    strengths: ['general', 'vision', 'code', 'reasoning'],
    contextWindow: 128000,
    envKey: 'OPENAI_API_KEY',
  },
  'gpt-4o-mini': {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    color: '#15803d',
    icon: '⚡',
    strengths: ['fast', 'general', 'cost-effective'],
    contextWindow: 128000,
    envKey: 'OPENAI_API_KEY',
  },
  // Google
  'gemini-pro': {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'google',
    color: '#2563eb',
    icon: '💎',
    strengths: ['research', 'multimodal', 'long-context'],
    contextWindow: 1000000,
    envKey: 'GOOGLE_API_KEY',
  },
  'gemini-flash': {
    id: 'gemini-1.5-flash',
    name: 'Gemini Flash',
    provider: 'google',
    color: '#1d4ed8',
    icon: '💎',
    strengths: ['fast', 'multimodal', 'cost-effective'],
    contextWindow: 1000000,
    envKey: 'GOOGLE_API_KEY',
  },
  // DeepSeek
  'deepseek-v3': {
    id: 'deepseek-chat',
    name: 'DeepSeek V3',
    provider: 'deepseek',
    color: '#7c3aed',
    icon: '🔬',
    strengths: ['code', 'math', 'reasoning'],
    contextWindow: 128000,
    envKey: 'DEEPSEEK_API_KEY',
  },
  'deepseek-v4-pro': {
    id: 'deepseek-reasoner',
    name: 'DeepSeek V4 Pro',
    provider: 'deepseek',
    color: '#6d28d9',
    icon: '🔬',
    strengths: ['complex-reasoning', 'math', 'research'],
    contextWindow: 128000,
    envKey: 'DEEPSEEK_API_KEY',
  },
  'deepseek-v4-flash': {
    id: 'deepseek-chat',
    name: 'DeepSeek V4 Flash',
    provider: 'deepseek',
    color: '#5b21b6',
    icon: '🔬',
    strengths: ['fast', 'code', 'cost-effective'],
    contextWindow: 64000,
    envKey: 'DEEPSEEK_API_KEY',
  },
  // MiniMax
  'minimax': {
    id: 'MiniMax-Text-01',
    name: 'MiniMax m.2.7',
    provider: 'minimax',
    color: '#0891b2',
    icon: '🌊',
    strengths: ['chinese', 'long-context', 'general'],
    contextWindow: 1000000,
    envKey: 'MINIMAX_API_KEY',
  },
  // ZhipuAI GLM
  'glm-4-7': {
    id: 'glm-4',
    name: 'GLM-4.7',
    provider: 'zhipuai',
    color: '#0e7490',
    icon: '🌐',
    strengths: ['chinese', 'general', 'reasoning'],
    contextWindow: 128000,
    envKey: 'ZHIPUAI_API_KEY',
  },
  'glm-5-1': {
    id: 'glm-4-plus',
    name: 'GLM-5.1',
    provider: 'zhipuai',
    color: '#155e75',
    icon: '🌐',
    strengths: ['chinese', 'advanced-reasoning', 'code'],
    contextWindow: 128000,
    envKey: 'ZHIPUAI_API_KEY',
  },
  // Alibaba Qwen
  'qwen-turbo': {
    id: 'qwen-turbo',
    name: 'Qwen Turbo',
    provider: 'qwen',
    color: '#b45309',
    icon: '🌸',
    strengths: ['fast', 'chinese', 'general'],
    contextWindow: 32000,
    envKey: 'DASHSCOPE_API_KEY',
  },
  'qwen-image': {
    id: 'wanx-v1',
    name: 'Qwen Image Edit',
    provider: 'qwen',
    color: '#92400e',
    icon: '🎨',
    strengths: ['image-generation', 'image-editing', 'creative'],
    contextWindow: 4000,
    envKey: 'DASHSCOPE_API_KEY',
  },
  // Mistral
  'mistral-large': {
    id: 'mistral-large-latest',
    name: 'Mistral Large',
    provider: 'mistral',
    color: '#be185d',
    icon: '🌪️',
    strengths: ['multilingual', 'code', 'reasoning'],
    contextWindow: 32000,
    envKey: 'MISTRAL_API_KEY',
  },
  // Moonshot Kimi
  'kimi-k2': {
    id: 'moonshot-v1-8k',
    name: 'Kimi-k2.6',
    provider: 'moonshot',
    color: '#9d174d',
    icon: '🌙',
    strengths: ['long-context', 'chinese', 'documents'],
    contextWindow: 128000,
    envKey: 'MOONSHOT_API_KEY',
  },
  // Meta Llama (via Groq)
  'llama-3-3': {
    id: 'llama-3.3-70b-versatile',
    name: 'Llama 3.3-70B',
    provider: 'groq',
    color: '#1e40af',
    icon: '🦙',
    strengths: ['fast', 'open-source', 'general'],
    contextWindow: 128000,
    envKey: 'GROQ_API_KEY',
  },
  'llama-4-scout': {
    id: 'meta-llama/llama-4-scout-17b-16e-instruct',
    name: 'Llama 4-Scout',
    provider: 'groq',
    color: '#1e3a8a',
    icon: '🦙',
    strengths: ['multimodal', 'fast', 'vision'],
    contextWindow: 131072,
    envKey: 'GROQ_API_KEY',
  },
  'llama-4': {
    id: 'meta-llama/llama-4-maverick-17b-128e-instruct',
    name: 'Llama 4',
    provider: 'groq',
    color: '#1e3a8a',
    icon: '🦙',
    strengths: ['advanced', 'multimodal', 'reasoning'],
    contextWindow: 131072,
    envKey: 'GROQ_API_KEY',
  },
  // NVIDIA
  'nvidia-nim': {
    id: 'nvidia/llama-3.1-nemotron-70b-instruct',
    name: 'NVIDIA NIM',
    provider: 'nvidia',
    color: '#76b900',
    icon: '🖥️',
    strengths: ['technical', 'scientific', 'code'],
    contextWindow: 128000,
    envKey: 'NVIDIA_API_KEY',
  },
  // ElevenLabs (TTS)
  'elevenlabs': {
    id: 'eleven_multilingual_v2',
    name: 'ElevenLabs Voice',
    provider: 'elevenlabs',
    color: '#6366f1',
    icon: '🎙️',
    strengths: ['voice-synthesis', 'tts', 'multilingual'],
    contextWindow: 0,
    envKey: 'ELEVENLABS_API_KEY',
  },
  // OpenAI Whisper (STT)
  'whisper': {
    id: 'whisper-1',
    name: 'Whisper STT',
    provider: 'openai',
    color: '#14532d',
    icon: '🎤',
    strengths: ['speech-to-text', 'transcription', 'multilingual'],
    contextWindow: 0,
    envKey: 'OPENAI_API_KEY',
  },
  // DALL-E
  'dalle-3': {
    id: 'dall-e-3',
    name: 'DALL-E 3',
    provider: 'openai',
    color: '#065f46',
    icon: '🎨',
    strengths: ['image-generation', 'creative', 'art'],
    contextWindow: 4000,
    envKey: 'OPENAI_API_KEY',
  },
};

// Smart routing: pick best model for task type
function routeModel(taskType, preferFast = false) {
  const routing = {
    code: preferFast ? 'deepseek-v4-flash' : 'claude-sonnet',
    writing: preferFast ? 'gpt-4o-mini' : 'claude-opus',
    research: preferFast ? 'gemini-flash' : 'gemini-pro',
    math: preferFast ? 'deepseek-v4-flash' : 'deepseek-v4-pro',
    image: 'dalle-3',
    'image-edit': 'qwen-image',
    voice: 'elevenlabs',
    transcription: 'whisper',
    chinese: preferFast ? 'qwen-turbo' : 'glm-5-1',
    reasoning: preferFast ? 'gpt-4o-mini' : 'claude-opus',
    general: preferFast ? 'gpt-4o-mini' : 'gpt-4o',
    fast: 'llama-3-3',
  };
  return routing[taskType] || (preferFast ? 'gpt-4o-mini' : 'claude-sonnet');
}

module.exports = { MODELS, routeModel };
