"""
JARVIS Flywheel Engine — compound growth tracker measuring how each business
segment reinforces the others in a self-accelerating growth cycle.
"""
from __future__ import annotations

import json
import logging
from datetime import date, datetime, timedelta, timezone
from typing import Any
from uuid import UUID

from app.core.database import AsyncSessionLocal, set_tenant_context

logger = logging.getLogger(__name__)

# ── Flywheel segments (in cycle order) ───────────────────────────────────────

FLYWHEEL_SEGMENTS = [
    "lead_quality",
    "outreach_precision",
    "proposal_conversion",
    "client_satisfaction",
    "referrals",
    "market_reputation",
]

SEGMENT_DESCRIPTIONS = {
    "lead_quality": "Quality and fit of incoming leads",
    "outreach_precision": "Effectiveness of outreach targeting and messaging",
    "proposal_conversion": "Rate at which proposals convert to paid clients",
    "client_satisfaction": "Delivered value and client happiness",
    "referrals": "Referrals generated by satisfied clients",
    "market_reputation": "Brand strength and market positioning",
}

# Base growth rates per flywheel velocity level
VELOCITY_GROWTH_RATES = {
    range(0, 3): {"leads": 0.02, "revenue": 0.015},
    range(3, 5): {"leads": 0.05, "revenue": 0.04},
    range(5, 7): {"leads": 0.08, "revenue": 0.07},
    range(7, 9): {"leads": 0.12, "revenue": 0.10},
    range(9, 11): {"leads": 0.18, "revenue": 0.15},
}


def _get_growth_rate(velocity: float) -> dict[str, float]:
    """Get monthly growth rate based on flywheel velocity."""
    vel_int = int(velocity)
    for vel_range, rates in VELOCITY_GROWTH_RATES.items():
        if vel_int in vel_range:
            return rates
    return {"leads": 0.05, "revenue": 0.04}


async def _fetch_segment_scores(tenant_id: UUID) -> dict[str, float]:
    """Fetch data from DB to calculate segment scores."""
    scores: dict[str, float] = {}

    async with AsyncSessionLocal() as session:
        await set_tenant_context(session, tenant_id)
        from sqlalchemy import text

        # Lead quality: score based on average lead score
        try:
            row = await session.execute(
                text("SELECT AVG(score) FROM leads WHERE tenant_id = :t AND score IS NOT NULL"),
                {"t": str(tenant_id)},
            )
            avg_score = row.scalar() or 50
            scores["lead_quality"] = min(10.0, float(avg_score) / 10.0)
        except Exception:
            scores["lead_quality"] = 5.0

        # Outreach precision: reply rate approximation
        try:
            row = await session.execute(
                text(
                    """
                    SELECT COUNT(*) FILTER (WHERE status = 'replied') * 10.0 / NULLIF(COUNT(*), 0)
                    FROM outreach_records WHERE tenant_id = :t
                    """
                ),
                {"t": str(tenant_id)},
            )
            reply_rate = row.scalar() or 0
            scores["outreach_precision"] = min(10.0, float(reply_rate) * 10.0)
        except Exception:
            scores["outreach_precision"] = 4.0

        # Proposal conversion: proposals sent vs won deals
        try:
            sent_row = await session.execute(
                text("SELECT COUNT(*) FROM proposals WHERE tenant_id = :t AND status = 'sent'"),
                {"t": str(tenant_id)},
            )
            won_row = await session.execute(
                text("SELECT COUNT(*) FROM proposals WHERE tenant_id = :t AND status = 'won'"),
                {"t": str(tenant_id)},
            )
            sent = sent_row.scalar() or 1
            won = won_row.scalar() or 0
            conversion_rate = won / sent if sent > 0 else 0
            scores["proposal_conversion"] = min(10.0, conversion_rate * 40)  # 25% = 10
        except Exception:
            scores["proposal_conversion"] = 3.0

        # Client satisfaction: proxy via active clients / total clients
        try:
            total_row = await session.execute(
                text("SELECT COUNT(DISTINCT company_id) FROM crm_contacts WHERE tenant_id = :t"),
                {"t": str(tenant_id)},
            )
            total = total_row.scalar() or 0
            scores["client_satisfaction"] = min(10.0, (total / 5) * 10) if total > 0 else 3.0
        except Exception:
            scores["client_satisfaction"] = 5.0

        # Referrals: leads with source = 'referral'
        try:
            ref_row = await session.execute(
                text(
                    "SELECT COUNT(*) FROM leads WHERE tenant_id = :t AND source = 'referral'"
                ),
                {"t": str(tenant_id)},
            )
            ref_count = ref_row.scalar() or 0
            scores["referrals"] = min(10.0, float(ref_count) * 0.5)
        except Exception:
            scores["referrals"] = 2.0

        # Market reputation: derived from intel entries and research reports
        try:
            intel_row = await session.execute(
                text("SELECT COUNT(*) FROM research_reports WHERE tenant_id = :t"),
                {"t": str(tenant_id)},
            )
            intel_count = intel_row.scalar() or 0
            scores["market_reputation"] = min(10.0, float(intel_count) * 0.8 + 3.0)
        except Exception:
            scores["market_reputation"] = 4.0

    return scores


class FlywheelEngine:
    """Compound growth tracker for Aliyar Solutions business flywheel."""

    async def calculate_flywheel_score(self, tenant_id: UUID) -> dict[str, Any]:
        """Calculate comprehensive flywheel velocity and momentum."""
        segment_scores = await _fetch_segment_scores(tenant_id)

        scores_list = list(segment_scores.values())
        if not scores_list:
            scores_list = [5.0] * len(FLYWHEEL_SEGMENTS)

        flywheel_velocity = round(sum(scores_list) / len(scores_list), 2)

        # Weakest link is the segment with lowest score
        weakest_link = min(segment_scores, key=segment_scores.get)
        strongest_segment = max(segment_scores, key=segment_scores.get)

        # Compound growth factor: product of normalized segment scores
        normalized = [s / 10.0 for s in scores_list]
        compound_factor = 1.0
        for n in normalized:
            compound_factor *= max(0.1, n)
        compound_growth_factor = round(compound_factor ** (1 / len(normalized)) * 2, 4)

        # Momentum trend based on weakest link impact
        weakest_score = segment_scores[weakest_link]
        if weakest_score >= 7:
            momentum_trend = "ACCELERATING"
        elif weakest_score >= 4:
            momentum_trend = "STABLE"
        else:
            momentum_trend = "DECELERATING"

        result = {
            "tenant_id": str(tenant_id),
            "flywheel_velocity": flywheel_velocity,
            "weakest_link": weakest_link,
            "weakest_link_description": SEGMENT_DESCRIPTIONS.get(weakest_link, ""),
            "weakest_link_score": round(segment_scores[weakest_link], 2),
            "strongest_segment": strongest_segment,
            "strongest_segment_score": round(segment_scores[strongest_segment], 2),
            "momentum_trend": momentum_trend,
            "compound_growth_factor": compound_growth_factor,
            "segment_scores": {k: round(v, 2) for k, v in segment_scores.items()},
            "calculated_at": datetime.now(timezone.utc).isoformat(),
        }

        # Persist snapshot
        await self._persist_snapshot(tenant_id, result)
        return result

    async def project_flywheel_growth(
        self,
        tenant_id: UUID,
        months: int = 12,
    ) -> list[dict[str, Any]]:
        """Project month-by-month flywheel-driven growth."""
        flywheel = await self.calculate_flywheel_score(tenant_id)
        velocity = flywheel["flywheel_velocity"]
        growth_rates = _get_growth_rate(velocity)

        # Fetch current baseline metrics
        async with AsyncSessionLocal() as session:
            await set_tenant_context(session, tenant_id)
            from sqlalchemy import text
            try:
                leads_row = await session.execute(
                    text("SELECT COUNT(*) FROM leads WHERE tenant_id = :t"),
                    {"t": str(tenant_id)},
                )
                current_leads = leads_row.scalar() or 10
            except Exception:
                current_leads = 10

            try:
                rev_row = await session.execute(
                    text(
                        "SELECT COALESCE(SUM(amount), 0) FROM invoices WHERE tenant_id = :t AND status = 'paid'"
                    ),
                    {"t": str(tenant_id)},
                )
                total_revenue = float(rev_row.scalar() or 0)
                current_monthly_revenue = total_revenue / 12 if total_revenue > 0 else 5000.0
            except Exception:
                current_monthly_revenue = 5000.0

        projections = []
        leads = float(current_leads)
        revenue = current_monthly_revenue
        current_velocity = velocity

        for month in range(1, months + 1):
            # Velocity improves slightly if momentum is accelerating
            if flywheel["momentum_trend"] == "ACCELERATING":
                current_velocity = min(10.0, current_velocity + 0.05)
            elif flywheel["momentum_trend"] == "DECELERATING":
                current_velocity = max(0.5, current_velocity - 0.03)

            current_rates = _get_growth_rate(current_velocity)
            leads = leads * (1 + current_rates["leads"])
            revenue = revenue * (1 + current_rates["revenue"])

            projections.append(
                {
                    "month": month,
                    "month_label": (
                        date.today().replace(day=1) + timedelta(days=30 * month)
                    ).strftime("%b %Y"),
                    "projected_leads": int(leads),
                    "projected_revenue": round(revenue, 2),
                    "flywheel_score": round(current_velocity, 2),
                }
            )

        return projections

    async def _persist_snapshot(self, tenant_id: UUID, data: dict) -> None:
        """Store flywheel snapshot in database."""
        try:
            import uuid as _uuid
            from sqlalchemy import text

            async with AsyncSessionLocal() as session:
                await set_tenant_context(session, tenant_id)
                await session.execute(
                    text(
                        """
                        INSERT INTO flywheel_snapshots
                          (id, tenant_id, flywheel_velocity, weakest_link, strongest_segment,
                           momentum_trend, compound_growth_factor, snapshot_date, created_at)
                        VALUES
                          (:id, :tenant_id, :velocity, :weakest, :strongest,
                           :trend, :compound, :snapshot_date, now())
                        """
                    ),
                    {
                        "id": str(_uuid.uuid4()),
                        "tenant_id": str(tenant_id),
                        "velocity": data["flywheel_velocity"],
                        "weakest": data["weakest_link"],
                        "strongest": data["strongest_segment"],
                        "trend": data["momentum_trend"],
                        "compound": data["compound_growth_factor"],
                        "snapshot_date": date.today(),
                    },
                )
                await session.commit()
        except Exception as exc:
            logger.warning("Failed to persist flywheel snapshot: %s", exc)


flywheel_engine = FlywheelEngine()
